### ISSUE TITLE
Additional examples explaining non-JSON input / file input

### ISSUE THREAD

**Issue by wwonigkeit** [vorteil/direktiv#10]
Could you please add an example of how to handle a binary file input / non-JSON input for use in workflows such as image rendering or manipulation.

**Comment by jamesjmurtagh** [comment]
This is documented, but is not easy to find (https://docs.direktiv.io/docs/walkthrough/conditional-transitions.html#instance-input).

I'll put together an article specifically about this, because this is not an uncommon scenario and should be more clearly documented.

**Comment by jamesjmurtagh** [comment]
The new document can be found [here](https://docs.direktiv.io/docs/examples/non-json-input.html).
