### ISSUE TITLE
helm needs HTTPS_PROXY, HTTP_PROXY,NO_PROXY values

### ISSUE THREAD

**Issue by jensg-st** [vorteil/direktiv#118]
**Describe the bug**

knative & isolates can not access internet behind proxy. HTTPS_PROXY, HTTP_PROXY,NO_PROXY values need to be part of helm values so we can modify the isolate template and knative-controller.

**Comment by woniupapa** [comment]
@jensg-st Yes,I think so, too. I live in China, and Helm is blocked by The GFW(Great Firewall of China)  in our country.I have to change the downloading address of the images in helm values.
