### ISSUE TITLE
Hourly schedule not working cron: "0 * * * *"

### ISSUE THREAD

**Issue by wwonigkeit** [vorteil/direktiv#12]
**Describe the bug**
Hourly schedule does not work

**To Reproduce**
1. Created a workflow:
    id: dad-jokes
    description: "" 
    start:
      type: scheduled
      cron: "0 * * * *"
2. Enabled workflow

**Expected behavior**
Expected to see a message every hour (on the hour) to the endpoint

**Screenshots**

![Screen Shot 2021-03-05 at 6 03 07 am](https://user-images.githubusercontent.com/11344997/110015954-96886200-7d78-11eb-9c1b-ee8a99e3f2e0.png)

**Additional context**
This is the Beta interface (wf.direktiv.io) but running the same workflow engine

**Comment by jensg-st** [comment]
covered by #13
