### ISSUE TITLE
direkcli not deleting workflows

### ISSUE THREAD

**Issue by wwonigkeit** [vorteil/direktiv#15]
**Describe the bug**
Cannot delete created workflows with the direkcli command line utility

**To Reproduce**
ubuntu@ip-172-31-30-28:~$ ./direkcli workflows list demo
+--------------+
|      ID      |
+--------------+
| pnt-invoke   |
| pnt-workflow |
+--------------+
ubuntu@ip-172-31-30-28:~$ ./direkcli workflows delete demo
Error: accepts 2 arg(s), received 1
Usage:
  direkcli workflows delete NAMESPACE ID [flags]

Flags:
  -h, --help   help for delete

Global Flags:
      --grpc string   ip and port for connection GRPC default is 127.0.0.1:6666

accepts 2 arg(s), received 1
ubuntu@ip-172-31-30-28:~$ ./direkcli workflows delete demo pnt-workflow
[Canceled] grpc: the client connection is closing
ubuntu@ip-172-31-30-28:~$ ./direkcli workflows delete demo pnt-invoke
[Canceled] grpc: the client connection is closing
ubuntu@ip-172-31-30-28:~$

**Expected behavior**
The workflow should be deleted

**Desktop (please complete the following information):**
 - Ubuntu 20

**Additional context**
Direktiv is running using Docker. Command used to run Direktiv is:
sudo docker run --privileged -p6666:6666 -eDIREKTIV_INGRESS_BIND=0.0.0.0:6666 -eDIREKTIV_ISOLATION=container vorteil/direktiv

**Comment by trentis** [comment]
Fixed in v0.1.2
