### ISSUE TITLE
CNCF TAG-Runtime: Presentation/Discussion

### ISSUE THREAD

**Issue by raravena80** [vorteil/direktiv#255]
I'm one of the co-chairs of the CNCF TAG-Runtime, I'm reaching out and think it would be great for you to present/discuss the project at one of our meetings. An overview of the project would be great.

Let me know if this something you'd be interested in doing (I'm aware that you have presented the vorteil project in the past, but this is a different project) If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by wwonigkeit** [comment]
I've added an entry to the first available slot in the agenda and sent through an email. Looking forward to it!
